# Generated by Django 3.2.9 on 2021-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, default='', max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
