# Generated by Django 3.2.6 on 2021-12-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_api', '0003_alter_inventory_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.AddField(
            model_name='currency',
            name='currency',
            field=models.CharField(default='NIS', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('BILL', 'BILL'), ('COIN', 'COIN')], max_length=5),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
